services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb+srv://hashmatcheema78952:BwlyfSzuS8Jie8g3@cluster0.bbwhuyy.mongodb.net/authDB?retryWrites=true&w=majority
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - FRONTEND_URL=${FRONTEND_URL}

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb+srv://hashmatcheema78952:BwlyfSzuS8Jie8g3@cluster0.bbwhuyy.mongodb.net/userDB?retryWrites=true&w=majority
      - PORT=3002
      - JWT_SECRET=${JWT_SECRET}

  frontend-service:
    build: ./frontend-service
    ports:
      - "5173:80"
    # volumes:
    #   - ./frontend-service:/app
    #   - /app/node_modules
    depends_on:
      - auth-service
      - user-service