apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: auth-service
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: auth-service
     template:
       metadata:
         labels:
           app: auth-service
       spec:
         containers:
         - name: auth-service
           image: auth-service
           ports:
           - containerPort: 3001
           env:
           - name: MONGODB_URI
             value: "mongodb+srv://hashmatcheema78952:BwlyfSzuS8Jie8g3@cluster0.bbwhuyy.mongodb.net/authDB?retryWrites=true&w=majority"
           - name: PORT
             value: "3001"
           - name: JWT_SECRET
             value: "267a0ba97cbf5e3e6098a5cc2e0178f453dbf7fb8e68956dac2d631561739cc0"
           - name: EMAIL_HOST
             value: "smtp.gmail.com"
           - name: EMAIL_PORT
             value: "587"
           - name: EMAIL_USER
             value: "velanginiamith@gmail.com"
           - name: EMAIL_PASS
             value: "pyqlamlwxzfqiqiz"
           - name: FRONTEND_URL
             value: "http://localhost:5173"
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: auth-service
   spec:
     ports:
     - port: 3001
       targetPort: 3001
     selector:
       app: auth-service
     type: NodePort