apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: frontend-service
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: frontend-service
     template:
       metadata:
         labels:
           app: frontend-service
       spec:
         containers:
         - name: frontend-service
           image: frontend-service
           ports:
           - containerPort: 5173
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: frontend-service
   spec:
     ports:
     - port: 5173
       targetPort: 5173
     selector:
       app: frontend-service
     type: NodePort